### PR TITLE
BOAC-4033: Allows category course units to be a numerical range

### PR DESCRIPTION
**Pull request by lyttam**
https://jira.ets.berkeley.edu/jira/browse/BOAC-4033

I opted not to add validation to ensure the 'min' is less than the 'max' - if a user decides to input '4-3', for example, that's on them.

### CODE REVIEW

**Comment by johncrossman** [comment]
@lyttam - What do you think of using Postgres builtin range type? https://medium.com/dataseries/range-types-in-postgresql-and-gist-indexes-788db23346c5   That would allow data integrity checks and help with the comparisons we'll need to do https://jira.ets.berkeley.edu/jira/browse/BOAC-3872   Thoughts?

**Comment by lyttam** [comment]
Good idea @johncrossman, I'll amend.

**Comment by lyttam** [comment]
@johncrossman I pushed some changes. Ready for another look.

**Comment by johncrossman** [comment]
Thank you @lyttam  Looks good. I'll merge when Travis gives the green.

**Pull request merged**
