### PR TITLE
BOAC-2433 Note search: resolve conflicts between advisor name/'Posted by you'

### PR DESCRIPTION
**Pull request by paulkerschen**
https://jira.ets.berkeley.edu/jira/browse/BOAC-2433

### CODE REVIEW

**Comment by paulkerschen** [comment]
Travis-side (https://travis-ci.com/ets-berkeley-edu/boac/builds/118330823), py-lint has had a mysterious failure starting up: `module 'pydocstyle' has no attribute 'tokenize_open'`. Have py-lint dependencies gotten scrambled under the hood?

**Comment by johncrossman** [comment]
@paulkerschen I could reproduce locally with `rm -Rf ./.tox/lint-py` and then run `tox -e lint-py`.  Those steps took me from `pydocstyle-3.0.0` to `pydocstyle-4.0.0` and the latter don't play nice.  I think we need to lock down that dep

**Comment by paulkerschen** [comment]
Thanks @johncrossman - I'll amend tox.ini and retry.

**Comment by johncrossman** [comment]
Waiting on Travis build: https://travis-ci.com/ets-berkeley-edu/boac/builds/118336943

**Pull request merged**
