### PR TITLE
BOAC-2993, fixes on appointment_events related SQL/API

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/BOAC-2993

The SQL script, with these fixes, has been run against boac-dev db. Front-end tweaks will follow.

### CODE REVIEW

**Comment by johncrossman** [comment]
I am going to amend this PR. Please hold off on merge.

**Comment by johncrossman** [comment]
This PR is ready for review. Once merged I intend to manually drop `appointment_event_types` in boac-dev and re-run the create enum portion of migration script.

**Comment by paulkerschen** [comment]
Simply enumptious.

**Comment by johncrossman** [comment]
The mini-script to manual migrate enum is posted to https://jira.ets.berkeley.edu/jira/browse/BOAC-2993

**Pull request merged**
