### PR TITLE
BOAC-4392, Degree progress: URLs in notes are linked in non-printable view

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/BOAC-4392

### CODE REVIEW

**Comment by lyttam** [comment]
@johncrossman I think category descriptions in the student worksheet and template builder also need to be linkified.

**Comment by johncrossman** [comment]
Thanks @lyttam  Amending

**Comment by johncrossman** [comment]
@lyttam - my amendment will go in next PR.

**Comment by lyttam** [comment]
Oops, I thought you were done amending.

**Pull request merged**
