### PR TITLE
BOAC-206, fix to myCohorts dropdowns broke filters dropdowns

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/BOAC-206

Cohort filters were impacted by new `.dropdown-menu > li > span` style. 

PR includes necessary `None` check `photo_api`.

### CODE REVIEW

**Comment by paulkerschen** [comment]
@johncrossman I opened #229 for a fix to the photo_api issue that should play nice with tests.

**Comment by raydavis** [comment]
@paulkerschen @johncrossman  Can one of you say more about "the photo_api issue"? I don't find any explanation in JIRA or code comments, but I gather from PR https://github.com/ets-berkeley-edu/boac/pull/229 that we can somehow end up with a raw HTTP response which has no `status_code` attribute, which seems kind of interesting.

**Comment by paulkerschen** [comment]
@raydavis In cases such as a timeout, raw_response can come back `None`.

As outlined at #229, a simple `if response.raw_response` doesn't work as a check for this case since error responses are falsey. That's what's causing the failing test at this PR.

#229 duck-types it by checking for a `status_code` attribute. I suppose `is not None` would work equally well.

**Comment by raydavis** [comment]
Thanks, @paulkerschen . I knew about not relying on a `response.raw_response` boolean (which is why that wasn't being used in other caching code), but hadn't seen the timeout response yet.

**Pull request closed without merging**
