### PR TITLE
BOAC-3098, get_sis_note_attachments: priority given to is_historical=FALSE (per SID, note_id)

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/BOAC-3098

### CODE REVIEW

**Comment by paulkerschen** [comment]
@johncrossman Tricky! Out of curiosity, is there any reason one couldn’t do the same thing directly in SQL using an aggregate function? Something like

{code}
SELECT advising_note_id, created_by, sis_file_name, user_file_name, MIN(is_historical)
...
GROUP BY advising_note_id, created_by, sis_file_name, user_file_name
{code}

**Comment by johncrossman** [comment]
@paulkerschen – I was looking for such magical SQL. In my tests, I found `MIN(...)` to be incompatible with type boolean. https://stackoverflow.com/questions/20281125/why-aggregate-functions-in-postgresql-do-not-work-with-boolean-data-type

I can play around a bit more.

**Comment by johncrossman** [comment]
Ah, I think `MIN(is_historical::int)` is the secret sauce.

**Comment by johncrossman** [comment]
I'll test then, if all good, amend the PR.

**Comment by paulkerschen** [comment]
There it is!

**Comment by johncrossman** [comment]
Amended

**Pull request merged**
