### PR TITLE
BOAC-2589: Adds pending_advisees table

### PR DESCRIPTION
**Pull request by lyttam**
https://jira.ets.berkeley.edu/jira/browse/BOAC-2589

### CODE REVIEW

**Comment by raydavis** [comment]
Question about the naming: does `pending_advisees` mean the table will be truncated once the SIDs show up in Nessie's regular nightly runs?

**Comment by lyttam** [comment]
@raydavis I guess it could go either way, but I was imagining we might want to do something like that.  "Pending" sounds temporary; it could be named `manually_added_advisees` if they are going to stay.

**Comment by paulkerschen** [comment]
@raydavis @lyttam My two cents are that the number of advisees might be small enough that we could just keep them around indefinitely, and skip the complication of syncing to Nessie, verifying the sync, and such.

**Comment by lyttam** [comment]
Sounds good to me.  I changed the name.

**Pull request merged**
