### PR TITLE
BOAC-92, rename 'cohorts' to 'teams' (w/ db modify script) - make way for custom cohorts 

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/BOAC-92

See JIRA comments.

Refactor will continue as we develop search and custom-cohorts.

### CODE REVIEW

**Comment by johncrossman** [comment]
Some lint-py love is needed. Please stand by.

**Comment by paulkerschen** [comment]
@johncrossman Following comments in the JIRA, I get wanting to rename the "Cohort" model, but "Team" seems confusing for a similar reason: you'd expect a single model object or database row to correspond to a single team, but what that database actually contains is a set of team memberships.

The comment "Team definitions and memberships" at the top of `team.py` seems like a red flag. The team code translations might want to live in a `team.py` file, but `team_members` or `team_memberships` seems like a clearer name for the db-backed model. (Is there a better term for this in the sports world?)

**Comment by johncrossman** [comment]
@paulkerschen We here in room 451 agree and I like `team_members`. Of course, the term "member" is already in use (sample below). We'll need minor terminology refactors in near future. Your vote is...?
```
    cohort = app.cache.get(cache_key) if (app.cache) else None
    if cohort is None:
        cohort = Team.for_code(cohort_code)
        for member in cohort['members']:
```

**Comment by paulkerschen** [comment]
I like `team_members`, @johncrossman. The odd behavior in the `Team.for_code` method must reflect the denormalized nature of the table, with team-specific information copied into every member row. Further cleanup is indeed called for, now that this table is looking less temporary than we first thought.

**Comment by johncrossman** [comment]
I'll close this, adjust and submit anew. Thanks, @paulkerschen

**Pull request closed without merging**
